### PR TITLE
Add Dockerfile

### LINKED ISSUE #179: Add Dockerfile and push to Docker hub
Hello 👋 

We use this CLI in CI and it would nice to have an official Docker image and build to use. Modern CIs like Concourse and Circle can easily use Docker images instead of having to curl bins.

### PR DESCRIPTION
**Pull request by arbourd**
The Dockerfile is built on alpine (pretty common for CLIs now) and comes
with bash, tzdata and ca-certs.

Closes #179

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thank you for this @arbourd.
Can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your file?

**Comment by arbourd** [comment]
Done.

**Comment by arbourd** [comment]
Hey @eyalbe4, any updates on this? Thanks!

**Comment by eyalbe4** [comment]
We'll need some more time to get to it @arbourd.

**Comment by arbourd** [comment]
Any updates @eyalbe4? 😬

**Comment by eyalbe4** [comment]
Thank you for this @arbourd!
We'll make the [Jenkinsfile](https://github.com/jfrog/jfrog-cli-go/blob/master/Jenkinsfile) publish a docker image for every JFrog CLI release.

**Pull request merged**
