### PR TITLE
fix for #251 make build on freebsd

### PR DESCRIPTION
**Pull request by antoinell**
Fixes [#251](https://github.com/jfrog/jfrog-cli-go/issues/251).

### CODE REVIEW

**Comment by antoinell** [comment]
Hello Eyal,

this is done,

Antoine

**Comment by antoinell** [comment]
Thanks for merging this in. 
Jfrog-cli has been updated to 1.20.1 in freebsd ports https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233036 with the patch. Later it should be possible to upgrade to a release which builds without patch.

**Comment by antoinell** [comment]
jfrog-cli is visible here in the freebsd ports tree https://github.com/freebsd/freebsd-ports/tree/master/devel/jfrog-cli .

**Comment by eyalbe4** [comment]
Awesome @antoinell. Thanks!
We have a new patch coming out soon.
We'll update this issue when it is out.

**Pull request merged**
