### PR TITLE
Make docker-push skip the docker login call if --apikey is passed wit…

### PR DESCRIPTION
**Pull request by djgilcrease**
Make docker-push skip the docker login call if --apikey is passed with no user/password

fixes: #352

### CODE REVIEW

**Comment by djgilcrease** [comment]
Any feedback, progress on merging this?

**Comment by eyalbe4** [comment]
@djgilcrease,
For compatibility reasons, JFrog CLI still allows using an API key without a username, however this is something we'd rather not support.
The ```jfrog rt c``` command no longer accepts an API key without a username.
We'd like to better understand the need for this requirement, so that we can come up with the best solution for it.
What is the reason you'd like to ```jfrog rt dp``` command to skip the login?

**Comment by djgilcrease** [comment]
Because;
1. The login does not work on older versions of docker
2. The login does not work with API Key, even if you pass in the username, it requires you to pass in a username and un-encrypted password, which is a no go for our system
3. As long as passing API Key without username is supported things need to work, not error out with auth issues, because the tool does not know how to perform the action.

**Comment by eyalbe4** [comment]
@djgilcrease - 
As for your comment #2 above - I've just tested the *docker-push* command with the a username and an API key and it seems to work as expected.
I did run a *docker logout* command before executing the command. Could this be the cause of the issue?
See below:  
```
ip-10-1-20-183:jfrog-cli-go eyalb$ docker -v
Docker version 18.06.0-ce, build 0ffa825
ip-10-1-20-183:jfrog-cli-go eyalb$ ./jfrog -v
jfrog version 1.25.0
ip-10-1-20-183:jfrog-cli-go eyalb$ docker logout ecosysjfrog-docker-local.jfrog.io
Removing login credentials for ecosysjfrog-docker-local.jfrog.io
WARNING: could not erase credentials: error erasing credentials - err: exit status 1, out: `The specified item could not be found in the keychain.`
WARNING: could not erase credentials: error erasing credentials - err: exit status 1, out: `The specified item could not be found in the keychain.`
ip-10-1-20-183:jfrog-cli-go eyalb$ 
ip-10-1-20-183:jfrog-cli-go eyalb$ ./jfrog rt dp ecosysjfrog-docker-local.jfrog.io/dockerhello-world:45 docker-local --url=https://ecosysjfrog.jfrog.io/ecosysjfrog/ --user=XXX --apikey=YYY
Login Succeeded
The push refers to repository [ecosysjfrog-docker-local.jfrog.io/dockerhello-world]
3af68cacae27: Pushed 
73ad47d4bc12: Layer already exists 
c22c27816361: Layer already exists 
04dba64afa87: Layer already exists 
500ca2ff7d52: Layer already exists 
782d5215f910: Layer already exists 
0eb22bfb707d: Layer already exists 
a2ae92ffcd29: Layer already exists 
45: digest: sha256:1e4b64e2f6c2649c43144fe6c043e282a590d1bed63da2e75ea478ae9a63d997 size: 1994
ip-10-1-20-183:jfrog-cli-go eyalb$ 
```

**Comment by djgilcrease** [comment]
Which version of docker do you have. I will double check, and upgrade to 1.25 of the cli to see

**Comment by djgilcrease** [comment]
Closing this in favor of #380

**Pull request closed without merging**
