### PR TITLE
Support retries in upload command

### PR DESCRIPTION
**Pull request by DimaNevelev**

### CODE REVIEW

**Comment by eyalbe4** [comment]
I've gone through the code. Looks good @DimaNevelev.

**Comment by BrBill** [comment]
As the _(a?)_ requester for this, you have my thanks for this, looking forward to trying the fix.

**Comment by scottrus** [comment]
Will this retry also apply to downloads or is it strictly uploads? We EOF errors during simple network events that will stop a download. If downloads can be retried that would be be a great solution.

**Comment by eyalbe4** [comment]
@scottrus,
Download retries ae already supported. The *jfrog rt download* command has the *--retry* option with a default value of 3. You can set it to a higher value if needed.

**Comment by scottrus** [comment]
Thanks @eyalbe4. That seems a bit odd that we see an EOF even after 3 retries then. I'll look into it more and file an issue if I think it's needed.

**Comment by eyalbe4** [comment]
Sounds good @scottrus. Your feedback can be helpful. See that the JFrog CLI version you're using includes the *--retry* option.

**Pull request merged**
